# -*- coding: utf-8 -*-
"""slm-journeyday21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YeSGUlZ3qtiMpy47xPDzpZSYE_guIyJ3


!pip install transformers==4.44.0 peft==0.12.0 trl==0.11.0 accelerate datasets bitsandbytes -q
print("Done ✅") """

import transformers
import trl
import peft
print(f"transformers: {transformers.__version__}")
print(f"trl: {trl.__version__}")
print(f"peft: {peft.__version__}")

from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import LoraConfig, get_peft_model, TaskType
import torch
import json
from datasets import Dataset

# Load model in float16 - no quantization
tokenizer = AutoTokenizer.from_pretrained(
    "microsoft/phi-2",
    trust_remote_code=True
)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    "microsoft/phi-2",
    torch_dtype=torch.float16,
    trust_remote_code=True,
)
model = model.to("cuda")
print(f"Model loaded ✅")
print(f"GPU memory: {torch.cuda.memory_allocated()/1e9:.2f} GB")

# Apply LoRA
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj"],
    bias="none"
)
model = get_peft_model(model, lora_config)
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total = sum(p.numel() for p in model.parameters())
print(f"Trainable: {trainable:,} ({trainable/total*100:.2f}%) ✅")

# Load dataset
with open('/content/fine_tune_ready.json', 'r') as f:
    raw_data = json.load(f)

dataset = Dataset.from_list(raw_data)
split = dataset.train_test_split(test_size=0.1, seed=42)
print(f"Dataset: {len(split['train'])} train samples ✅")

from trl import SFTTrainer
from transformers import TrainingArguments

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=split['train'],
    dataset_text_field="text",
    max_seq_length=256,
    args=TrainingArguments(
        output_dir="./output",
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=20,
        max_steps=200,
        learning_rate=2e-4,
        fp16=True,
        logging_steps=20,
        optim="adamw_8bit",
        report_to="none",
        eval_strategy="no",
    ),
)

print("Training started 🔥")
print("200 steps — 10-15 minutes...")
stats = trainer.train()
print("Training complete ✅")
print(f"Loss: {stats.metrics['train_loss']:.4f}")
print(f"Time: {stats.metrics['train_runtime']:.0f} seconds")

from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    device=0
)

prompts = [
    "### Instruction:\nClassify this news article.\n\n### Input:\nTesla announces record breaking EV sales this quarter.\n\n### Response:",
    "### Instruction:\nWhat is deep learning?\n\n### Response:",
    "### Instruction:\nSummarize this text:\n\n### Input:\nNeural networks learn from data through backpropagation.\n\n### Response:",
]

for prompt in prompts:
    result = pipe(
        prompt,
        max_new_tokens=60,
        temperature=0.7,
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id
    )
    response = result[0]['generated_text'][len(prompt):]
    print(f"Prompt:   {prompt[-60:]}")
    print(f"Response: {response[:100]}")
    print()

model.save_pretrained("/content/phi2_finetuned_day21")
tokenizer.save_pretrained("/content/phi2_finetuned_day21")
print("Model saved ✅")